# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6c663963e1837bc50b4037467873724f0f25a524f2a214806aea776a07c971a3f7c337eefe39c2d043e93247a5f42959c9e3946d591ad04a3223666b22b99745
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>

  basic_auth_user: <%= ENV["BASIC_AUTH_USER"] %>
  basic_auth_password: <%= ENV["BASIC_AUTH_PASSWORD"] %>

  recaptcha_site_key: <%= ENV["RECAPTCHA_SITE_KEY"] %>
  recaptcha_secret_key: <%= ENV["RECAPTCHA_SECRET_KEY"] %>

  payjp_private_key: <%= ENV["PAYJP_PRIVATE_KEY"] %>

  facebook_key: <%= ENV["FACEBOOK_KEY"] %>
  facebook_secret: <%= ENV["FACEBOOK_SECRET"] %>

  google_client_id: <%= ENV["GOOGLE_CLIENT_ID"] %>
  google_client_secret: <%= ENV["GOOGLE_CLIENT_SECRET"] %>

  twilio_number: <%= ENV["TWILIO_NUMBER"] %>
  twilio_sid: <%= ENV["TWILIO_SID"] %>
  twilio_token: <%= ENV["TWILIO_TOKEN"] %>

test:
  secret_key_base: 6c663963e1837bc50b4037467873724f0f25a524f2a214806aea776a07c971a3f7c337eefe39c2d043e93247a5f42959c9e3946d591ad04a3223666b22b99745

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>

  basic_auth_user: <%= ENV["BASIC_AUTH_USER"] %>
  basic_auth_password: <%= ENV["BASIC_AUTH_PASSWORD"] %>

  recaptcha_site_key: <%= ENV["RECAPTCHA_SITE_KEY"] %>
  recaptcha_secret_key: <%= ENV["RECAPTCHA_SECRET_KEY"] %>

  payjp_private_key: <%= ENV["PAYJP_PRIVATE_KEY"] %>

  facebook_key: <%= ENV["FACEBOOK_KEY"] %>
  facebook_secret: <%= ENV["FACEBOOK_SECRET"] %>

  google_client_id: <%= ENV["GOOGLE_CLIENT_ID"] %>
  google_client_secret: <%= ENV["GOOGLE_CLIENT_SECRET"] %>

  twilio_number: <%= ENV["TWILIO_NUMBER"] %>
  twilio_sid: <%= ENV["TWILIO_SID"] %>
  twilio_token: <%= ENV["TWILIO_TOKEN"] %>

